version: "3.9"
services:
  generate_ros_msgs_ros2dart:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
      args:
        - CATKIN_WORKSPACE_DIR=${CATKIN_WORKSPACE_DIR}
        # - USERNAME=developer
        - USERNAME=${USERNAME:-developer}
        - UID=${UID:-1000}
        - GID=${UID:-1000}
    container_name: generate_ros_msgs_ros2dart
    environment:
      - ROS_MASTER_URI=http://${ROBOT_IP}:11311
      - ROS_IP=${YOUR_IP}
    extra_hosts:
      - "${ROBOT_HOSTNAME}:${ROBOT_IP}"
    image: generative_ros_msgs:devel
    network_mode: "host"
    tty: true
    volumes:
      - ../src:/${CATKIN_WORKSPACE_DIR}/src
      - ../artifacts/build:/${CATKIN_WORKSPACE_DIR}/build
      - ../artifacts/devel:/${CATKIN_WORKSPACE_DIR}/devel
      - ../ros/:/${CATKIN_WORKSPACE_DIR}/ros:rw

